#
# This source file is part of the My Heart Counts Android open-source project
#
# SPDX-FileCopyrightText: 2026 Stanford University and the project authors (see CONTRIBUTORS.md)
#
# SPDX-License-Identifier: MIT
#

name: Android Build, Test, and Analysis

on:
  workflow_dispatch:
  workflow_call:

jobs:
  android:
    name: Android
    # Pins the feature revision until the .github repository tags v0.6.
    uses: SchmiedmayerLab/.github/.github/workflows/android.yml@ec38544f6872d95105981440c79b28df7fe63486
    permissions:
      actions: read
      contents: read
      packages: read
      security-events: write
    secrets: inherit
    with:
      submodules: 'true'
      swiftversion: 'latest'
