#
# This source file is part of the My Heart Counts open-source project
#
# SPDX-FileCopyrightText: 2026 Stanford University and the project authors (see CONTRIBUTORS.md)
#
# SPDX-License-Identifier: MIT
#

name: Static Analysis

on:
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  reuse:
    name: REUSE Compliance
    uses: SchmiedmayerLab/.github/.github/workflows/reuse.yml@v0.3
    permissions:
      contents: read

  markdown_links:
    name: Markdown Links
    uses: SchmiedmayerLab/.github/.github/workflows/markdown-links.yml@v0.3
    permissions:
      contents: read
      pull-requests: read
